export const getOpenings = (userProfile, jobData) => {

  const openings = [
    `I am writing to express my enthusiasm for the ${jobData.jobTitle} position at ${jobData.company}.`,
    `It is with great interest that I submit my application for the ${jobData.jobTitle} role at ${jobData.company}.`,
    `Having followed ${jobData.company}'s impressive growth, I am excited to apply for the ${jobData.jobTitle} position.`,
    `Your posting for a ${jobData.jobTitle} at ${jobData.company} immediately captured my attention as it aligns perfectly with my career goals.`,
    `As a professional with extensive experience in ${userProfile.skills[0]} and ${userProfile.skills[1]}, I am thrilled to apply for the ${jobData.jobTitle} position at ${jobData.company}.`,
    `I am pleased to submit my application for the ${jobData.jobTitle} position at ${jobData.company}, as I believe my skills align well with the role.`,
    `With a strong background in ${userProfile.skills[0]} and ${userProfile.skills[1]}, I am eager to contribute to ${jobData.company} as a ${jobData.jobTitle}.`,
    `I am writing to formally express my interest in the ${jobData.jobTitle} position at ${jobData.company}.`,
    `The opportunity to join ${jobData.company} as a ${jobData.jobTitle} is one that greatly interests me, given my expertise in ${userProfile.skills[0]}.`,
    `I am excited to apply for the ${jobData.jobTitle} role at ${jobData.company} and contribute my skills and experience to your team.`,
    `Please accept my application for the ${jobData.jobTitle} position at ${jobData.company}. I am confident that my background makes me a strong candidate.`,
    `With extensive experience in ${userProfile.skills[0]}, I am eager to bring my expertise to ${jobData.company} in the role of ${jobData.jobTitle}.`,
    `I am very interested in the ${jobData.jobTitle} opportunity at ${jobData.company} and am excited about the prospect of joining your team.`,
    `Having researched ${jobData.company} and its initiatives, I am highly motivated to apply for the ${jobData.jobTitle} position.`,
    `I am honored to submit my application for the ${jobData.jobTitle} position at ${jobData.company}, as I believe my qualifications closely match your requirements.`,
    `I am excited about the possibility of joining ${jobData.company} as a ${jobData.jobTitle} and contributing to your continued success.`,
    `With a proven track record in ${userProfile.skills[0]}, I am eager to bring my expertise to ${jobData.company} in the ${jobData.jobTitle} role.`,
    `I am writing to express my interest in the ${jobData.jobTitle} opportunity at ${jobData.company}, as I believe my skills would be a valuable addition to your team.`,
    `I would like to formally submit my application for the ${jobData.jobTitle} position at ${jobData.company} and highlight how my experience aligns with the role.`,
    `It would be a privilege to bring my knowledge and experience to ${jobData.company} as a ${jobData.jobTitle}.`,
    `I am reaching out to express my enthusiasm for the ${jobData.jobTitle} opportunity at ${jobData.company} and my interest in contributing to your organization.`,
    `I am pleased to submit my application for the ${jobData.jobTitle} role at ${jobData.company}, as I am confident that my expertise will add value to your team.`,
    `With a deep appreciation for the work done at ${jobData.company}, I am eager to apply for the ${jobData.jobTitle} role.`,
    `I would welcome the opportunity to apply my skills and experience in ${userProfile.skills[0]} to the ${jobData.jobTitle} position at ${jobData.company}.`,
    `I am excited to apply for the ${jobData.jobTitle} position at ${jobData.company} and believe that my experience in ${userProfile.skills[0]} makes me an excellent fit.`,
    `I am submitting my application for the ${jobData.jobTitle} role at ${jobData.company} with great enthusiasm and confidence in my ability to contribute.`,
    `It is with genuine interest that I submit my application for the ${jobData.jobTitle} position at ${jobData.company}.`,
    `I am honored to apply for the ${jobData.jobTitle} position at ${jobData.company} and look forward to the opportunity to discuss how my skills align with your needs.`,
    `The ${jobData.jobTitle} role at ${jobData.company} presents an exciting opportunity, and I am eager to bring my expertise in ${userProfile.skills[0]} to your team.`,
    `I am highly motivated to apply for the ${jobData.jobTitle} position at ${jobData.company} and contribute my knowledge to your esteemed organization.`,
    `The reputation of ${jobData.company} as an industry leader makes the ${jobData.jobTitle} position an exciting prospect for me.`,
    `I am eager to apply my expertise in ${userProfile.skills[0]} to the ${jobData.jobTitle} role at ${jobData.company}.`,
    `I am submitting my application for the ${jobData.jobTitle} position at ${jobData.company} and look forward to the possibility of joining your team.`,
    `I am enthusiastic about the opportunity to apply for the ${jobData.jobTitle} role at ${jobData.company}, where I can contribute my experience in ${userProfile.skills[0]}.`,
    `I am excited by the prospect of bringing my skills in ${userProfile.skills[0]} to ${jobData.company} as a ${jobData.jobTitle}.`,
    `I have long admired the work of ${jobData.company} and am eager to contribute in the ${jobData.jobTitle} role.`,
    `It is with great enthusiasm that I submit my application for the ${jobData.jobTitle} position at ${jobData.company}, given my background in ${userProfile.skills[0]}.`,
    `I was drawn to the ${jobData.jobTitle} position at ${jobData.company} because of its alignment with my professional experience and career aspirations.`,
    `I am eager to bring my expertise in ${userProfile.skills[0]} to the ${jobData.jobTitle} role at ${jobData.company} and contribute to your mission.`,
    `I am pleased to submit my application for the ${jobData.jobTitle} position at ${jobData.company}, as I am confident my skills align with your needs.`,
    `My background in ${userProfile.skills[0]} makes me a strong candidate for the ${jobData.jobTitle} role at ${jobData.company}, and I am excited to apply.`,
    `I am excited about the opportunity to join ${jobData.company} in the ${jobData.jobTitle} position and leverage my expertise to support your objectives.`,
    `I am writing to express my interest in the ${jobData.jobTitle} position at ${jobData.company} and to highlight how my skills align with this role.`,
    `The prospect of joining ${jobData.company} as a ${jobData.jobTitle} excites me, as I believe my background in ${userProfile.skills[0]} will be beneficial to your team.`,
    `I am highly interested in the ${jobData.jobTitle} opportunity at ${jobData.company} and confident that my qualifications make me a strong fit.`,
    `I am writing to apply for the ${jobData.jobTitle} role at ${jobData.company} and look forward to the opportunity to discuss my qualifications further.`,
    `I am eager to bring my passion for ${userProfile.skills[0]} to ${jobData.company} in the role of ${jobData.jobTitle}.`,
    `My experience in ${userProfile.skills[0]} makes me a great fit for the ${jobData.jobTitle} position at ${jobData.company}, and I am excited about this opportunity.`,
    `The ${jobData.jobTitle} role at ${jobData.company} aligns with my professional background and aspirations, making it an ideal opportunity for me.`,
    `I am eager to explore the opportunity to join ${jobData.company} as a ${jobData.jobTitle} and contribute to your team.`,
    `I am applying for the ${jobData.jobTitle} position at ${jobData.company} with enthusiasm and confidence in my ability to succeed in the role.`,
    `My extensive experience in ${userProfile.skills[0]} and ${userProfile.skills[1]} makes me excited to apply for the ${jobData.jobTitle} position at ${jobData.company}.`
  ];

  return openings[Math.floor(Math.random() * openings.length)];
}


export const getClosings = (jobData) => {

  const closings = [
    `I would welcome the opportunity to discuss how my background, skills, and experience would be beneficial to ${jobData.company}. Thank you for considering my application.`,
    `I am excited about the possibility of bringing my unique perspective and expertise to ${jobData.company} and would appreciate the chance to discuss my qualifications further.`,
    `I believe my combination of skills and passion makes me an ideal candidate for this role. I look forward to the opportunity to contribute to ${jobData.company}'s continued success.`,
    `Thank you for considering my application. I am eager to explore how my background aligns with the goals of ${jobData.company} and would welcome a conversation at your convenience.`,
    `I look forward to the possibility of contributing to ${jobData.company} and would love the opportunity to discuss how my skills can benefit your team.`,
    `I appreciate your time and consideration, and I hope to have the chance to speak with you further about how I can contribute to ${jobData.company}.`,
    `I am excited about the potential to work with ${jobData.company} and would be happy to provide further details on my qualifications in an interview.`,
    `I would love the opportunity to bring my expertise to ${jobData.company} and discuss how I can add value to your team.`,
    `Thank you for your time. I would be delighted to further discuss how my experience and skills align with the needs of ${jobData.company}.`,
    `I am eager to join ${jobData.company} and would appreciate the chance to discuss my fit for this role in more detail.`,
    `It would be an honor to contribute to ${jobData.company}. I look forward to the opportunity to speak with you soon.`,
    `I appreciate your time and consideration and hope to have the opportunity to further discuss how I can support ${jobData.company}'s goals.`,
    `I look forward to the possibility of joining ${jobData.company} and would welcome the opportunity to discuss my candidacy further.`,
    `I would be delighted to bring my skills and enthusiasm to ${jobData.company} and look forward to the chance to speak with you.`,
    `I am confident that my background aligns well with this role, and I would appreciate the opportunity to discuss how I can contribute to ${jobData.company}.`,
    `I am excited about the opportunity to contribute to ${jobData.company}'s success and would welcome the chance to discuss my application in more detail.`,
    `I look forward to the possibility of joining your team and contributing to ${jobData.company}. Thank you for your time and consideration.`,
    `I appreciate the opportunity to apply for this role and hope to discuss my qualifications further with the hiring team at ${jobData.company}.`,
    `Thank you for reviewing my application. I am eager to discuss how my expertise aligns with ${jobData.company}'s needs.`,
    `I would love the chance to be a part of ${jobData.company} and would welcome the opportunity to speak with you further.`,
    `I am enthusiastic about this role and would love the chance to share how my skills align with ${jobData.company}’s needs.`,
    `I hope to bring my experience and insights to ${jobData.company}. I look forward to the opportunity to discuss further.`,
    `I am confident that my skills and experience will make a positive impact at ${jobData.company}. I look forward to hearing from you.`,
    `I am eager to explore how my skills and expertise can contribute to ${jobData.company}'s success. Thank you for your time and consideration.`,
    `I would be grateful for the chance to discuss how my qualifications align with the goals of ${jobData.company}.`,
    `I appreciate your time in reviewing my application and hope to have the opportunity to discuss my fit for this role.`,
    `I am excited about the chance to contribute to ${jobData.company} and look forward to discussing how I can be an asset to your team.`,
    `I would be honored to bring my experience to ${jobData.company} and would love the opportunity to discuss this role further.`,
    `I look forward to the possibility of working with the talented team at ${jobData.company} and contributing to its success.`,
    `I am eager to bring my passion and expertise to ${jobData.company} and hope to discuss my application in more detail.`,
    `Thank you for your time and consideration. I hope to have the chance to discuss my potential contributions to ${jobData.company}.`,
    `I welcome the opportunity to speak with you further and explore how I can add value to ${jobData.company}.`,
    `I appreciate the opportunity to apply for this position and look forward to the possibility of contributing to ${jobData.company}.`,
    `I am looking forward to the chance to join ${jobData.company} and make a meaningful impact. Thank you for your consideration.`,
    `I am eager to take on new challenges and believe ${jobData.company} is the perfect place for me to grow and contribute.`,
    `Thank you for considering my application. I would love the chance to discuss how my skills can support ${jobData.company}.`,
    `I am truly excited about this opportunity and would love to discuss my application further with the team at ${jobData.company}.`,
    `I appreciate your time and consideration and look forward to learning more about how I can contribute to ${jobData.company}.`,
    `I hope to have the opportunity to bring my experience and passion to ${jobData.company} and would love to speak with you soon.`
  ];

  return closings[Math.floor(Math.random() * closings.length)];
}
